p8105_hw2_co2616
================
2025-10-04

# Problem 1

loading the tidyverse and lubridate libraries to complete problem 1

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.2     ✔ tibble    3.3.0
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.1.0     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(lubridate)
```

tidying `pols` dataset

``` r
pols_df = 
  read_csv("hw2_data/pols-month.csv") %>% 
  janitor::clean_names() %>% 
  separate(
    mon, into = c("year", "month", "day")) %>% 
  mutate(
    month = case_match(
    month,
    "01" ~ "january",
    "02" ~ "february",
    "03" ~ "march",
    "04" ~ "april",
    "05" ~ "may",
    "06" ~ "june",
    "07" ~ "july",
    "08" ~ "august",
    "09" ~ "september",
    "10" ~ "october",
    "11" ~ "november",
    "12" ~ "december"
  )) %>% 
  pivot_longer(
    cols = c(prez_gop, prez_dem),
    names_to = "president",
    values_to = "party",
    names_prefix = "prez_"
  ) %>% 
  select(-day)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

tidying `snp` dataset

``` r
snp_df = 
  read_csv("hw2_data/snp.csv") %>% 
  janitor::clean_names() %>% 
  mutate(date = mdy(date)) %>% 
  separate(
    date, into = c("year", "month", "day")) %>%
  mutate(
    month = case_match(
    month,
    "01" ~ "january",
    "02" ~ "february",
    "03" ~ "march",
    "04" ~ "april",
    "05" ~ "may",
    "06" ~ "june",
    "07" ~ "july",
    "08" ~ "august",
    "09" ~ "september",
    "10" ~ "october",
    "11" ~ "november",
    "12" ~ "december")) %>% 
  relocate("year", "month") %>% 
  select(-day)
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

tidying `unemployment` dataset

``` r
unemploy_df = 
  read_csv("hw2_data/unemployment.csv") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    cols = jan:dec,
    names_to = "month",
    values_to = "percentage",
  ) %>% 
 mutate(
    month = case_match(
    month,
    "jan" ~ "january",
    "feb" ~ "february",
    "mar" ~ "march",
    "apr" ~ "april",
    "may" ~ "may",
    "jun" ~ "june",
    "jul" ~ "july",
    "aug" ~ "august",
    "sep" ~ "september",
    "oct" ~ "october",
    "nov" ~ "november",
    "dec" ~ "december")) %>% 
  mutate(year = as.character(year))
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

joining the datasets

``` r
first_df = 
  left_join(snp_df, pols_df, by = c("year", "month")) %>% 
  left_join(unemploy_df, by = c("year", "month"))
```

The `pols` dataset contained 822 observations of 9 variables related to
the number of national politicians who are democratic or republican at
any given time. The `snp` dataset contained 787 observations of 2
variables related to Standard & Poor’s stock market index (S&P). The The
`unemployment` dataset contained 68 observations of 13 variables related
to percentage of unemployment. After merging all three datasets together
the result dataset, `first_df`, contained 1,345 observations and 12
variables. The key variables were “year” and “month” and years ranged
from 1969 to 2068.
